# Generated by Django 3.2.7 on 2021-09-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypeModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='SVG File Name')),
                ('contenttype', models.CharField(max_length=50, verbose_name='Content Type')),
                ('svgfile', models.FileField(upload_to='contentypes/', verbose_name='SVG File Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'ContentType Icon',
                'verbose_name_plural': 'ContentType Icons',
            },
        ),
    ]
