# Generated by Django 3.2.7 on 2021-09-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filepathmodel',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='filepathmodel',
            name='filesize',
            field=models.IntegerField(default=1, verbose_name='File Size'),
            preserve_default=False,
        ),
    ]
